---
- name: Ensure unzip is installed
  package:
      name: unzip
      state: present

- name: Check Terraform Version
  shell: |
      set -o pipefail
      terraform --version | head -n 1 | awk 'print $2'
  register: terraform_version_check
  changed_when: terraform_version_check.stdout != terraform_version
  ignore_errors: true

- name: Download Terraform
  unarchive:
      src: "{{ terraform_download_url }}"
      dest: "{{ terraform_bin_path }}"
      remote_src: true
  when: terraform_version_check.stdout != terraform_version

- name: Verify Terraform is installed
  shell: |
      {{ terraform_bin_path }}/terraform --version
  when: terraform_version_check.stdout != terraform_version
