---
- name: Ensure unzip is installed
  package:
      name: unzip
      state: present

- name: Verify Terraform is not installed
  package:
    name:
      - terraform
    state: absent

- name: Download Terraform
  unarchive:
      src: "{{ terraform_download_url }}"
      dest: "{{ terraform_bin_path }}"
      remote_src: true
