---
- name: Ensure unzip is installed
  package:
      name: unzip
      state: present

- name: Check Terraform Version
  command: terraform --version | head -n 1 | awk '{print $2}'
  register: terraform_version_check
  changed_when: terraform_version_check.stdout != terraform_version
  failed_when: false

- name: Download Terraform
  unarchive:
      src: "{{ terraform_download_url }}"
      dest: "{{ terraform_bin_path }}"
      remote_src: true
  when: terraform_version_check.stdout != terraform_version
