---
- name: Ensure unzip is installed
  package:
      name: unzip
      state: present

- name: Check Terraform Version
  command: "terraform --version |awk 'NR==1{print $2}' |cut -dv -f2|cut -d' ' -f1"
  register: terraform_version_check
  changed_when: terraform_version_check.stdout != terraform_version

- name: Download Terraform
  unarchive:
      src: "{{ terraform_download_url }}"
      dest: "{{ terraform_bin_path }}"
      remote_src: true
  when: terraform_version_check.stdout != terraform_version
